# Generated by Django 3.2 on 2021-10-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_two', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.ManyToManyField(to='select_two.Language', verbose_name='Favourite Language')),
            ],
        ),
    ]
