# Generated by Django 3.2 on 2022-03-30 16:39

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='tags',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
