# Generated by Django 3.2 on 2021-10-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='a_party',
            field=models.PositiveIntegerField(verbose_name='APARTY'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='b_party',
            field=models.PositiveIntegerField(verbose_name='BPARTY'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='ci_start_a',
            field=models.PositiveIntegerField(verbose_name='CISTARTA'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='imei',
            field=models.PositiveIntegerField(verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='imsia',
            field=models.PositiveIntegerField(verbose_name='IMSIA'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='lac_start_a',
            field=models.PositiveIntegerField(verbose_name='LACSTARTA'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='mcc_start_a',
            field=models.PositiveIntegerField(verbose_name='MCCSTARTA'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='mnc_start_a',
            field=models.PositiveIntegerField(verbose_name='MNCSTARTA'),
        ),
    ]
