# Generated by Django 3.2 on 2021-10-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandling', '0002_auto_20211017_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='call_duration',
            field=models.PositiveIntegerField(verbose_name='CALL DURATION'),
        ),
    ]
