# Generated by Django 3.2 on 2021-10-17 05:36

from django.db import migrations, models
import apps.excelhandling.utils


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandling', '0003_alter_userinformation_call_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.excelhandling.utils.excel_file_directory_path)),
            ],
        ),
    ]
