# Generated by Django 3.2 on 2021-10-17 05:37

from django.db import migrations, models
import apps.excelhandling.utils


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandling', '0004_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to=apps.excelhandling.utils.excel_file_directory_path, verbose_name='Excel File'),
        ),
    ]
