# Generated by Django 3.2 on 2021-11-15 11:08

from django.db import migrations, models
import multiple_image.utils


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskimage',
            name='image',
            field=models.ImageField(upload_to=multiple_image.utils.images_directory_path),
        ),
    ]
