# Generated by Django 3.2 on 2021-10-17 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandling', '0005_alter_excelfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='a_party',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='APARTY'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ADDRESS'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='b_party',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='BPARTY'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='call_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CALL DURATION'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='ci_start_a',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CISTARTA'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excelfile',
            name='imei',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='IMEI'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='imsia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='IMSIA'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='lac_start_a',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='LACSTARTA'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='mcc_start_a',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MCCSTARTA'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='mnc_start_a',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MNCSTARTA'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='network_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Network TYPE'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='provider_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PROVIDER NAME'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='usage_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='USAGE TYPE'),
        ),
    ]
