# Generated by Django 3.2 on 2021-10-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelhandling', '0006_auto_20211017_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='a_party',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='b_party',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='call_duration',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='ci_start_a',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='imsia',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='lac_start_a',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='mcc_start_a',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='mnc_start_a',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='network_type',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='excelfile',
            name='usage_type',
        ),
    ]
