# Generated by Django 3.2 on 2022-03-31 10:52

import apps.authotp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authotp', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.authotp.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
